blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/nutrimentor/nutrimentor/discussions
    about: Ideas, showcase (how you use NutriMentor in class), and general chat
